name: alien_chaos
description: Click the Aliens.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vibration: ^1.7.3  # Downgraded to a version that should be compatible
  material_color_utilities: ^0.8.0
  meta: ^1.12.0
  sqflite: ^2.0.0+3
  provider: any
  flutter_launcher_icons: ^0.11.0  # Downgraded to a compatible version
  path: ^1.8.0
  shake: ^2.2.0
  flutter_fortune_wheel: any
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/alien.png"

dependency_overrides:
  material_color_utilities: ^0.8.0
  meta: 1.12.0

flutter:
  uses-material-design: true
  assets:
    - assets/alien.png
    - assets/loading_screen.png
    - assets/images/wheel.png
