name: alien_chaos
description: Click the Aliens.


publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  material_color_utilities: ^0.8.0
  meta: ^1.12.0
  sqflite: ^2.0.0+3
  provider: any
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/alien.png"

dependency_overrides:
  material_color_utilities: ^0.8.0
  meta: 1.12.0

flutter:
  uses-material-design: true
  assets:
    - assets/alien.png
